root: true

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

extends:
  - eslint:recommended
  - google
  - next
  - next/core-web-vitals
  - prettier

overrides:
  # TypeScript
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - "@typescript-eslint"
    parser: "@typescript-eslint/parser"
    rules:
      # 保留: 戻り値の明示的指定
      "@typescript-eslint/explicit-module-boundary-types": off
      # _ から始まるもの、スプレッドによるプロパティ削除を許容
      "@typescript-eslint/no-unused-vars":
        - warn
        - varsIgnorePattern: "^_"
          argsIgnorePattern: "^_"
          ignoreRestSiblings: true

  # Jest
  # expect 等々...
  - files: ["*.test.ts", "*.test.tsx"]
    extends:
      - plugin:jest/recommended
    plugins:
      - jest

# 保留
rules:
  # jsdoc を書く
  valid-jsdoc: 0
  require-jsdoc: 0
  # class 内の this (?)
  no-invalid-this: 0
  # Next.js の Image コンポーネントを使用する
  "@next/next/no-img-element": 0
  # React のデバッグ用表示名
  react/display-name: off
