root: true

# VSCode ESLint 対応
# コンフィグファイルの `require` 等でエラー表示されないよう
env:
  node: true

extends:
  - eslint:recommended
  - google
  - next
  - next/core-web-vitals
  - prettier

overrides:
  # VSCode ESLint 対応
  # .js でエラー表示されないように .ts にのみ適応
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      # 戻り値の明示的指定
      "@typescript-eslint/explicit-module-boundary-types": off
      # _ から始まるもの、スプレッドによるプロパティ削除を許容
      "@typescript-eslint/no-unused-vars":
        - warn
        - varsIgnorePattern: "^_"
          argsIgnorePattern: "^_"
          ignoreRestSiblings: true

# 保留
rules:
  # 型定義読み込み (e.g. next-env.d.ts)
  spaced-comment: ["error", "always", { "markers": ["/"] }]
  # jsdoc を書く
  valid-jsdoc: 0
  require-jsdoc: 0
  # class 内の this (?)
  no-invalid-this: 0
  # Next.js の Image コンポーネントを使用する
  "@next/next/no-img-element": 0
  # React のデバッグ用表示名
  react/display-name: off
  # runtypes
  new-cap: 0
